php:
  image: php:8.1.2-apache
  container_name: meu-php
  ports:
    - "8000:80"
    - "443:443"
  volumes:
    - /home/gustavo/Documentos/GitHub/Lista-2-Desafios/Lista 2/Desafio 2:/var/www/html
  links:
    - db

db:
  image: mysql:latest
  container_name: meu-mysql
  ports:
    - "3306:3306"
  volumes:
    - /var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
